POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço",
    "description": "Alguma descrição",
    "price": 1600,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6887d2b28
###
DELETE http://localhost:3000/api/services/6887d1050a58693f0720a790

###
PUT http://localhost:3000/api/services/6887d2b281b2dc8d29370dc9
Content-Type: application/json

{
    "name": "Algum serviço atualizado",
    "description": "Alguma descrição atualizada",
    "price": 16000,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Joelson",
    "description": "Uma festa de aniversario",
    "budget": 9000,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição",
            "price": 3000,
            "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição",
            "price": 1600,
            "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/688a82db232e060a80bc8a5b

###
DELETE http://localhost:3000/api/parties/688a83ad232e060a80bc8a5b

###

PUT http://localhost:3000/api/parties/688a82db232e060a80bc8a5b
Content-Type: application/json

{
    "title": "Meu evento 3",
    "author": "Joelson",
    "description": "Uma festa de aniversario",
    "budget": 9000,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição",
            "price": 3000,
            "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição",
            "price": 1600,
            "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCLHZeA--7ckaEIUPD-Z0XASJ5BxYQYLsdA&s"
        }
    ]
}